### ISSUE TITLE
Зачем вам эта переменная?

### ISSUE THREAD

**Issue by coursar** [Nikrom13/Homework#2]
https://github.com/Nikrom13/Homework/blob/d5c608e9187ee61b159ce751fbcc91a934101b4c/src/main/java/ru/itpark/CalculateBonus.java#L10

**Comment by Nikrom13** [comment]
В нее кладу то сколько надо вовзратить клиенту бонусов, она ниже расчитывается

**Comment by coursar** [comment]
Почему сразу не делать return?

**Comment by coursar** [comment]
Если исправили, закрывайте

**Comment by coursar** [comment]
Надо сделать merge в master
