### ISSUE TITLE
Вы делите currentPurchase / 1000 в трёх местах. Вынесите повторяющийся код в одно выражение

### ISSUE THREAD

**Issue by coursar** [Nikrom13/Homework#4]
https://github.com/Nikrom13/Homework/blob/d5c608e9187ee61b159ce751fbcc91a934101b4c/src/main/java/ru/itpark/CalculateBonus.java#L18

**Comment by Nikrom13** [comment]
Выполнил d3bd360cceb5ba2d77a0047d0300b0f62a93200f

**Comment by coursar** [comment]
Закрывайте Issue сообщениями коммитов, а не комментариями к Issue. У вас есть специальное видео.
